### ISSUE TITLE
how do I configure 'runner pane'

### ISSUE THREAD

**Issue by tjaartvdwalt** [syohex/emacs-emamux#22]
Hi, excuse me if this is a noob question.

I am trying to use `emamux:run-command`. After I type my command I get the error "You are not in 'tmux'". I am not sure how to configure this to work.

**Comment by tjaartvdwalt** [comment]
ah ok I think I understand now... it works if I run emacs within a tmux terminal. I presume it is not possible to use `emamux:run-command` from a graphical emacs?

**Comment by syohex** [comment]
Yes it is impossible from a graphical emacs.

**Comment by tjaartvdwalt** [comment]
ok, thanks for clarifying that.
