### ISSUE TITLE
iterm tmux and emamux:run-command

### ISSUE THREAD

**Issue by indigoviolet** [syohex/emacs-emamux#39]
Iterm has nice tmux integration (https://gitlab.com/gnachman/iterm2/wikis/TmuxIntegration, it maps tmux windows to iterm tabs, and tmux panes to iterm panes). With this, and running emacs in the terminal, I'd have expected `run-command` and the runner pane to work, but it doesn't. Any idea why?

**Comment by indigoviolet** [comment]
Actually, if you start `env TMUX="foo" tmux -CC` it seems to work

**Comment by syohex** [comment]
I suppose to set TMUX environment variable is not necessary.
