### ISSUE TITLE
Is it possible to recognize 'tmux' when an emacsclient is inside a tmux session?

### ISSUE THREAD

**Issue by sriramkswamy** [syohex/emacs-emamux#42]
I can run commands and regions if I start a new Emacs instance within an already existing tmux session using `emacs -nw`. However, if I start an Emacs daemon outside of tmux and start a client inside emacs like so - `emacsclient -t`, I get the error that I'm not in 'tmux'. The weird part is the I can still split the tmux pane, create a new window and clone the current frame. Is it not possible to run commands when a client is open inside tmux?

**Comment by syohex** [comment]
Sorry too late reply..

No way. Environment variable of Emacs which is launched by `emacsclient -t` is same as `emacs --daemon` process. If daemon process does not launch within tmux, daemon process does not has tmux environment variable in it.

Workaround: You launch Emacs daemon process with tmux.

**Comment by sriramkswamy** [comment]
Ah, I see. Yes, I have been using that workaround for a while. Thanks!
